### ISSUE TITLE
supervised learning sample code in Lua

### ISSUE THREAD

**Issue by jaberg** [clementfarabet/ipam-tutorials#1]
Day2 is the supervised learning day. I think we have a good assignment idea (play with optimization of convnet for cifar10 or google street signs (gss)) but we need code.

**Comment by jaberg** [comment]
hey @clementfarabet, I took the liberty of assigning you this one. I'm working on some unsupervised learning sample code to do rbms and autoencoders and stuff. I'm not sure how to break it down into files, but I just picked something, figuring that we could discuss that sort of thing after we got some raw content in place.

**Comment by clementfarabet** [comment]
@jaberg, sounds good, I'm finalizing a couple of scripts to work on cigar, g street signs, and mnist. They're pretty much the same, except a few details that hold for natural images. Will commit this stuff soon.

**Comment by clementfarabet** [comment]
Ok, so I put 3 scripts in th_tutorials/1_supervised/. These three scripts all do the same thing, on three different datasets (MNIST, CIFAR and HouseNumbers). We'll only look at one over the tutorial of course. The scripts are pretty much self-contained: they're quite verbose, but on purpose. Instead of relying on classes, most of the code is exposed right there. I'm writing html tutorials on the side, to accompany the scripts.

Let me know what you think, it's still a bit raw.

**Comment by jaberg** [comment]
On Sun, Jul 1, 2012 at 3:33 AM, Clement Farabet
reply@reply.github.com
wrote:

> Ok, so I put 3 scripts in th_tutorials/1_supervised/. These three scripts all do the same thing, on three different datasets (MNIST, CIFAR and HouseNumbers). We'll only look at one over the tutorial of course. The scripts are pretty much self-contained: they're quite verbose, but on purpose. Instead of relying on classes, most of the code is exposed right there. I'm writing html tutorials on the side, to accompany the scripts.
> 
> Let me know what you think, it's still a bit raw.
> 
> Ok, I'll have a look at this stuff after the soccer game :)

Writing verbose code is better than hiding functionality in classes I
think, but you're right it's a balancing act. How much html tutorial
are you aiming for? Feel free to cut and paste out of the Deep
Learning Tutorials. (I should have mentioned them before if you
haven't seen them)

https://github.com/lisa-lab/DeepLearningTutorials
http://deeplearning.net/tutorial/

There's a lot of good math and figures there. I'm only redoing
anything because I really like what my new "pyautodiff" project makes
possible. I think writing algorithms in pure numpy and then optimizing
them with theano makes theano more usable (essentially making it
disappear).

That brings up another potential topic for the last day - "looking
under the hood."  I could talk a little about how the sample code from
days2 and 3 works, to give students a sense of where to start when
things go wrong. I could easily make it hands-on (a debugging
assignment??) but I also have my standard Theano talk that I could
give at that point. I think it makes more sense to talk about how
Theano works, and how one might want to extend it on the last day,
rather than the first.

**Comment by clementfarabet** [comment]
OK thanks for the pointers, I knew about these tutorials, I'll have a look again.

Cool that you have an autodiff package now, that's really nice.
