### ISSUE TITLE
confusion.totalValid is set to zero before it is logged

### ISSUE THREAD

**Issue by rolfe** [clementfarabet/ipam-tutorials#16]
confusion.totalValid is set to zero by confusion:zero() before it is logged in trainLogger.   I've included the relevant code excerpt below.

-- print confusion matrix
   print(confusion)
   confusion:zero()

   -- update logger/plot
   trainLogger:add{['% mean class accuracy (train set)'] = confusion.totalValid \* 100}

**Comment by clementfarabet** [comment]
The Torch tutorials (code) were moved to https://github.com/clementfarabet/torch-tutorials, and the text moved to http://code.cogbits.com/wiki .

This bug was fixed there.
