### ISSUE TITLE
decide on assignment for unsupervised learning

### ISSUE THREAD

**Issue by jaberg** [clementfarabet/ipam-tutorials#2]

**Comment by jaberg** [comment]
@clementfarabet on my side I spent most of today working on this and I'm about half-done... I think the unsupervised learning exercise is just going to be playing with different filter-learning algorithms, and comparing them on their aesthetics. 

I'm trying to make it so that it's easy to drop in various strategies for training (I've got about 6 so far I think). With the possibility of using a few data sets, there's plenty of material to explore.

You can learn nice features in a few seconds to a few minutes, which is fast enough to be fun. Play with the l2 and l1 weight regularization to get pretty ones. Play with pre-processing the input. It's not quantitative, but it's a lot faster than training classifiers on top of everything.

**Comment by jaberg** [comment]
Also, I'm really hoping that the coding style I used can be somewhat consistent with the supervised learning stuff. Let me know when you have a draft I can check out.

My not-entirely-functional script is here:
https://github.com/clementfarabet/ipam-tutorials/blob/py_unsup/py_unsup/q_beauty_contest.py

**Comment by clementfarabet** [comment]
So I committed the supervised script under th_tutorials/1_supervised/.

I think that you've got much more material on the unsup side than I do, so we could probably balance the 2 middle days like this: I could spend more time on the supervised stuff (day 2), and you could spend more time on the unsup stuff (day 3). What do you think? On the unsup side, I can put together an extension of the house number script, which pre-trains an auto encoder to initialize layer(s) 1 (and 2).

**Comment by jaberg** [comment]
On Sun, Jul 1, 2012 at 3:36 AM, Clement Farabet
reply@reply.github.com
wrote:

> So I committed the supervised script under th_tutorials/1_supervised/.
> 
> I think that you've got much more material on the unsup side than I do, so we could probably balance the 2 middle days like this: I could spend more time on the supervised stuff (day 2), and you could spend more time on the unsup stuff (day 3). What do you think? On the unsup side, I can put together an extension of the house number script, which pre-trains an auto encoder to initialize layer(s) 1 (and 2).

This sounds good, I think we're in good shape to keep students engaged
and entertained for an hour. I agree we don't need everything in both
languages.

I still have to make the street numbers dataset available in my
dataset project, and bring in some patch-whitening code from another
project, but then things should be shaping up to learn some pretty
Gabors with each of the algorithms.

Actually sparse coding is still notimplemented too, but I think there
are other higher priorities - like figuring out the general program :)

**Comment by clementfarabet** [comment]
> Actually sparse coding is still notimplemented too, but I think there
> are other higher priorities - like figuring out the general program :)

Hé hé :-) I agree, it doesn't matter to have everything, better to have a couple of simple tasks that make the whole thing nice and entertaining.
