### ISSUE TITLE
configure EC2 machine

### ISSUE THREAD

**Issue by jaberg** [clementfarabet/ipam-tutorials#4]
I don't really know how to do this, but there are people here to get tips from.

**Comment by clementfarabet** [comment]
Cool, I created an account, and it looks fairly straightforward. Pricing is a bit obscure though. I guess we'll get the bill once we're done :-).

**Comment by jaberg** [comment]
Wow great. I haven't used my account in a while I was going to tackle
this tomorrow. IIRC there is a single-core machine instance that is
very cheap, and what costs money is mainly the virtual drive instance
(how many GB is your filesystem?)

What I'm not clear on is the difference between the writable drives
and the volatile drive images. The former are more expensive but more
conventional, the latter, cheaper but mega-scalable. I'm not clear on
how it works if multiple instances of a single writable drive image
are launched... they obviously can't both persist their changes it
would be like running two computers off of the same HD.

On Sun, Jul 1, 2012 at 3:37 AM, Clement Farabet
reply@reply.github.com
wrote:

**Comment by clementfarabet** [comment]
> Wow great. I haven't used my account in a while I was going to tackle
> this tomorrow. IIRC there is a single-core machine instance that is
> very cheap, and what costs money is mainly the virtual drive instance
> (how many GB is your filesystem?)
> 
> What I'm not clear on is the difference between the writable drives
> and the volatile drive images. The former are more expensive but more
> conventional, the latter, cheaper but mega-scalable. I'm not clear on
> how it works if multiple instances of a single writable drive image
> are launched... they obviously can't both persist their changes it
> would be like running two computers off of the same HD.

mmm, ok, I actually hadn't found the volatile solution. Let me look into
this again.
